# Generated by Django 5.0.3 on 2024-03-19 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materiales', '0004_alter_material_urlimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='material',
            name='cantidad',
            field=models.IntegerField(default=0),
        ),
    ]
